apiVersion: batch/v1
kind: Job
metadata:
  name: init-flash-sale-topic
  namespace: kafka-scenario
spec:
  template:
    spec:
      restartPolicy: OnFailure
      containers:
        - name: init-topic
          image: bitnami/kafka:3.7
          command: ["/bin/bash", "-ec"]
          args:
            - |
              for i in $(seq 1 30); do
                kafka-topics.sh --bootstrap-server kafka.kafka-scenario.svc.cluster.local:9092 --list && break
                echo "waiting kafka..."
                sleep 3
              done
              kafka-topics.sh \
                --bootstrap-server kafka.kafka-scenario.svc.cluster.local:9092 \
                --create --if-not-exists \
                --topic flash-sale-orders \
                --partitions 6 \
                --replication-factor 1
