apiVersion: v1
kind: Pod
metadata:
  name: affinity-required
  namespace: sched-lab
spec:
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
          - matchExpressions:
              - key: zone
                operator: In
                values: ["test-a"]
  containers:
    - name: app
      image: nginx:1.27
---
apiVersion: v1
kind: Pod
metadata:
  name: affinity-preferred
  namespace: sched-lab
spec:
  affinity:
    nodeAffinity:
      preferredDuringSchedulingIgnoredDuringExecution:
        - weight: 100
          preference:
            matchExpressions:
              - key: dedicated
                operator: In
                values: ["general"]
  containers:
    - name: app
      image: nginx:1.27
