apiVersion: v1
kind: Pod
metadata:
  name: prod-like-scheduling
  namespace: sched-lab
spec:
  tolerations:
    - key: workload
      operator: Equal
      value: isolated
      effect: NoSchedule
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
          - matchExpressions:
              - key: zone
                operator: In
                values: ["test-b"]
  containers:
    - name: app
      image: nginx:1.27
      resources:
        requests:
          cpu: "200m"
          memory: "256Mi"
